### ISSUE TITLE
Run first npm i jasmine

### ISSUE THREAD

**Issue by wbartussek** [MaciejWWojcik/subscription-component-schematics#1]
Using VS Code I ran into a bunch errors when issuing 'npm run build' as the first command. After having run 'npm i jasmine', 'npm run build' would finish without errors. So in the sense of "first things first" I would like to propose to first run 'npm i jasmine' and to update the README.md accordingly.

**Comment by MaciejWWojcik** [comment]
Hey :)
I believe it's not really about the jasmine, but about installing dependencies at all, before you run the build command.
I agree that no information about that could be misleading, so will definitely update the readme file.

Cheers!
